import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * We just use one sidebar for all the docs.
 * If we end up having a lot more docs we might want to break it down.
 */
const sidebars: SidebarsConfig = {
  sidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
